FROM python:3.9-slim

ENV WEAVIATE_URL=http://weaviate:8080

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ARG GIT_TAG=Survey-Response-UI
RUN git clone https://github.com/ArjunBakhale/gpt-semantic-search.git --branch $GIT_TAG --single-branch  .

RUN pip3 install -r requirements.txt
RUN pip3 install slack_bolt

LABEL \
    org.opencontainers.image.title="JaneliaGPT Slack Bot" \
    org.opencontainers.image.description="Slack bot for Janelia GPT Semantic Search" \
    org.opencontainers.image.authors="rokickik@janelia.hhmi.org" \
    org.opencontainers.image.licenses="BSD-3-Clause" \
    org.opencontainers.image.version=${GIT_TAG} 

CMD ["python", "slack_app.py"]