version: '3.4'
services:

  weaviate:
    image: semitechnologies/weaviate:1.24.4
    ports:
    - 8777:8080
    restart: unless-stopped
    volumes:
      - ${WEAVIATE_STORAGE_PATH:-./storage/weaviate}:/var/lib/weaviate
    environment:
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      QUERY_DEFAULTS_LIMIT: 25
      CLUSTER_HOSTNAME: 'node1'
      DISABLE_TELEMETRY: 'true'
      LIMIT_RESOURCES: 'true'

  semantic-search:
    image: ghcr.io/janeliascicomp/gpt-semantic-search-web:0.1.4
    ports:
    - 8501:8501
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: 'none'
      STREAMLIT_SERVER_HEADLESS: 'true'
      WEAVIATE_URL: 'http://weaviate:8080'
      OPENAI_API_KEY:
      SLACK_TOKEN:

  slack-bot:
    image: ghcr.io/janeliascicomp/gpt-semantic-search-slack-bot:0.1.6
    restart: unless-stopped
    environment:
      WEAVIATE_URL: 'http://weaviate:8080'
      OPENAI_API_KEY: 
      SLACK_BOT_TOKEN: 
      SLACK_APP_TOKEN: 
      SLACK_TOKEN:
    depends_on:
      - weaviate
    # volumes:
    #   - ./slack_app.py:/app/slack_app.py:ro
    #   - ./generate_full_response.py:/app/generate_full_response.py:ro

# To push an update to the docker image, run the following command and fill in the blanks:
# docker buildx build --push --build-arg GIT_TAG=0.1.5 --progress=plain --platform linux/arm64,linux/amd64 --tag ghcr.io/janeliascicomp/gpt-semantic-search-___:0._._ -f Dockerfile_ .
# docker buildx build --push --platform linux/arm64,linux/amd64 --tag ghcr.io/janeliascicomp/gpt-semantic-search-slack-bot:0.1.5 -f Dockerfile_slack .

# docker buildx build --push --build-arg GIT_TAG=0.1.6 --progress=plain --platform linux/arm64,linux/amd64 --tag ghcr.io/janeliascicomp/gpt-semantic-search-slack-bot:0.1.6 -f Dockerfile_slack .