[project]
authors = ["Arjun Bakhale <arjun.bakhale@gmail.com>", "Krun onrad Rokicki <rokickik@hhmi.org>"]
channels = ["conda-forge"]
name = "gpt-semantic-search"
platforms = ["osx-arm64", "linux-aarch64", "linux-64", "osx-64"]
version = "0.1.0"

[dependencies]
# Python version constraint
python = "3.9.*"

# packages from conda-forge
pandas = "==2.2.2"
beautifulsoup4 = "==4.12.3"
httpx = "==0.27.2"
numpy = "<2.0.0"

[pypi-dependencies]
llama-index-embeddings-openai = "==0.1.7"
llama-index-llms-openai = ">=0.1.22,<0.1.29"
llama-index-vector-stores-weaviate = "<0.1.8"
llama-index-core = ">=0.10.50"
deepeval = "<3.1.3"
weaviate-client = ">=3.26.2,<4.0.0"
openai = ">=1.30.1,<1.40.0"
streamlit = "==1.32.2"
slack-sdk = "==3.27.1"
scrapy = "==2.11.1"
html2text = "==2024.2.26"
slack-bolt = "*"
